name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Briefcase
      run: pip install briefcase

    - name: Build Android App
      run: briefcase build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TVApp-android-apk
        path: dist/*.apk

